### ISSUE TITLE
Fix line per line

### ISSUE THREAD

**Issue by salteadorneo** [salteadorneo/PlayJS#15]
Casos conocidos:

https://playjs.dev/aG9sYU11bmRvKCkKCmZ1bmN0aW9uIGhvbGFNdW5kbyAoKSB7CiAgICByZXR1cm4gJ/CfkYvwn4yOJwp9

https://playjs.dev/aG9sYU11bmRvKCkKCmNvbnN0IGhvbGFNdW5kbyA9ICgpID0+ICfwn5GL8J+Mjic=

**Comment by Dhruvn-patel** [comment]
Traditional Function Declaration:
`// Call the function before defining it
sayHello(); // This works!

// Define the function
function sayHello() {
  console.log("Hello from traditional function!");
}

// Call the function after defining it
sayHello(); // This also works!
`

In this example, we first call the sayHello function before defining it. This works because of a feature called function hoisting in JavaScript. Function declarations are hoisted to the top of their containing scope, so they can be used before they are defined in the code. This is a unique feature of traditional function declarations.

ES6 Arrow Function
`// Call the arrow function before defining it - This won't work!
sayHi(); // Error: sayHi is not a function

// Define the arrow function
const sayHi = () => {
  console.log("Hi from arrow function!");
};

// Call the arrow function after defining it
sayHi(); // This works!
`

In contrast to traditional function declarations, arrow functions are not hoisted. When we attempt to call the sayHi arrow function before defining it, we get an error because it's not recognized as a function. Arrow functions must be defined before they are used.

So, the key difference between these two approaches is that traditional function declarations can be called before they are defined due to hoisting, while arrow functions must be defined before they are used in the code. This behavior impacts the order in which you can call and define functions in your JavaScript code.



I hope this help you
